# Generated by Django 4.0.3 on 2023-07-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_salesperson_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='custom_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
